### PR TITLE
Code to prevent duplicate processing.

### PR DESCRIPTION
**Pull request by matthew-ivre**
The problem is that the code to process the string is being run twice. The second execution seems to be triggered by the hover event.

The first run correctly processes the string.

The second run takes the already processed string and breaks it.

Barry tested a version of this solution and it seemed to work, but it would need more testing in the ENGAGE project.

**Note**: The fix may not be needed if we can prevent the second processing on the Gizmo strings. There's a flag in RTLTextMeshPro.UpdateText that should probably be set to false after the update. That may be enough to prevent multiple processing.

### CODE REVIEW

**Comment by matthew-ivre** [comment]
Should resolve both EN-43590 and EN-43593. But needs testing.

**Comment by matthew-ivre** [comment]
Could you please test @BenIVRE. Or suggest an alternative approach.

**Review by BenIVRE — CHANGES_REQUESTED** [review]
Changes will need to be applied to RTLTextMeshPro3D.cs also.

**Comment by matthew-ivre** [comment]
Changes applied to RTLTextMeshPro3D.cs

**Review by BenIVRE — APPROVED** [review]

**Review by dean-ivre — APPROVED** [review]

**Pull request merged**
